# Generated by Django 4.2.16 on 2024-12-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "submission",
            "0085_alter_article_jats_article_type_override_and_more",
        ),
        ("oas", "0002_switchboardmessage_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchboardmessage",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="submission.article",
            ),
        ),
    ]
