name: Formatting and linting
on:
  - push

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
            requirements-files: "requirements.txt"
            configuration: "--check-only --profile=black --line-length=79"
  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
            args: "--check --line-length 79 ."
